import axios from 'axios';

export default {
    name: 'imagine',
    description: 'Generate AI images',
    execute: async (sock, msg, args, context) => {
        if (args.length === 0) {
            return await sock.sendMessage(context.from, {
                text: '⚠️ Please provide a prompt!\nUsage: .imagine <description>\n\nExample: .imagine a cat wearing sunglasses'
            }, { quoted: msg });
        }
        
        const prompt = args.join(' ');
        
        await sock.sendMessage(context.from, {
            text: '🎨 Generating image... This may take a moment...'
        }, { quoted: msg });
        
        try {
            // Using Pollinations AI (free image generation)
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true`;
            
            const response = await axios.get(imageUrl, {
                responseType: 'arraybuffer',
                timeout: 60000
            });
            
            await sock.sendMessage(context.from, {
                image: Buffer.from(response.data),
                caption: `🎨 **AI Generated Image**\n\nPrompt: "${prompt}"\n\nGenerated by Nexora AI`
            }, { quoted: msg });
            
        } catch (error) {
            console.error('Image generation error:', error);
            await sock.sendMessage(context.from, {
                text: `❌ Failed to generate image!

Alternatives to try:
1. Get Stability AI API key
2. Use DALL-E API from OpenAI
3. Use Midjourney

Your prompt: "${prompt}"`
            }, { quoted: msg });
        }
    }
};
